// Populates the database with enough realistic-looking data (users, groups,
// posts, comments, messages) so the app looks like a real social network
// during the project defense. Safe to re-run - it wipes and rebuilds.
//
// Usage:  npm run seed

require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const User = require('./models/User');
const Group = require('./models/Group');
const Post = require('./models/Post');
const Comment = require('./models/Comment');
const Message = require('./models/Message');

const CITIES = ['Tel Aviv', 'Jerusalem', 'Haifa', 'Ramat Gan', 'Beer Sheva', 'Rosh HaAyin', 'Netanya'];
const CATEGORIES = ['tech', 'sports', 'music', 'travel', 'food', 'gaming', 'study'];
const COLORS = ['#6c5ce7', '#00b894', '#e17055', '#0984e3', '#d63031', '#e84393', '#00cec9'];

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function pickSome(arr, n) { return [...arr].sort(() => Math.random() - 0.5).slice(0, n); }

async function run() {
  await connectDB();

  console.log('Clearing existing collections...');
  await Promise.all([User.deleteMany({}), Group.deleteMany({}), Post.deleteMany({}), Comment.deleteMany({}), Message.deleteMany({})]);

  console.log('Creating users...');
  const names = ['dana', 'omri', 'yossi', 'maya', 'noa', 'itay', 'shira', 'tom', 'liron', 'roy', 'gal', 'yael', 'eden', 'amit', 'nir'];
  const users = [];
  for (const name of names) {
    const user = await User.create({
      username: name,
      email: `${name}@example.com`,
      password: 'password123',
      bio: `Hi, I'm ${name}! Just here to share what I love.`,
      city: pick(CITIES),
      age: 18 + Math.floor(Math.random() * 30),
      avatarColor: pick(COLORS),
      role: 'user'
    });
    users.push(user);
  }
  // Promote a few demo accounts so every role can be shown during the defense.
  await User.create({ username: 'admin', email: 'admin@example.com', password: 'admin123', role: 'admin', city: 'Tel Aviv', age: 30, bio: 'System administrator' });
  users[0].role = 'manager'; await users[0].save();
  users[1].role = 'manager'; await users[1].save();

  console.log('Building friendships...');
  for (const user of users) {
    const friends = pickSome(users.filter((u) => String(u._id) !== String(user._id)), 3 + Math.floor(Math.random() * 4));
    user.friends = friends.map((f) => f._id);
    await user.save();
    for (const f of friends) { f.friends.addToSet(user._id); await f.save(); }
  }

  console.log('Creating groups...');
  const groupNames = ['Node.js Israel', 'Weekend Hikers', 'Home Cooking Club', 'Retro Gaming', 'Startup Founders', 'Guitar Players'];
  const groups = [];
  for (const name of groupNames) {
    const manager = pick(users);
    const group = await Group.create({
      name,
      description: `A community of people who love ${name.toLowerCase()}.`,
      category: pick(CATEGORIES),
      privacy: Math.random() > 0.5 ? 'public' : 'private',
      manager: manager._id,
      members: pickSome(users, 4 + Math.floor(Math.random() * 6)).map((u) => u._id),
      pendingMembers: pickSome(users, 2).map((u) => u._id)
    });
    group.members.addToSet(manager._id);
    await group.save();
    groups.push(group);
  }

  console.log('Creating posts...');
  const titles = ['Check this out', 'My weekend project', 'Anyone else seeing this?', 'Big update', 'Question for the community', 'Loved this so much', 'Quick tip', 'Throwback'];
  const posts = [];
  const now = new Date();
  for (let i = 0; i < 60; i++) {
    const author = pick(users);
    const group = Math.random() > 0.5 ? pick(groups.filter((g) => g.members.some((id) => String(id) === String(author._id)))) : null;
    const monthsAgo = Math.floor(Math.random() * 6);
    const createdAt = new Date(now.getFullYear(), now.getMonth() - monthsAgo, 1 + Math.floor(Math.random() * 27));
    const post = await Post.create({
      title: `${pick(titles)} #${i + 1}`,
      content: 'This is a demo post generated by the seed script so the network feels alive during the defense.',
      category: pick(CATEGORIES),
      author: author._id,
      group: group ? group._id : null,
      likes: pickSome(users, Math.floor(Math.random() * 8)).map((u) => u._id),
      createdAt
    });
    posts.push(post);
  }
  // Force createdAt through direct update since Mongoose timestamps override it on create.
  for (const post of posts) { await Post.updateOne({ _id: post._id }, { $set: { createdAt: post.createdAt } }); }

  console.log('Creating comments...');
  for (const post of posts) {
    const commenters = pickSome(users, Math.floor(Math.random() * 4));
    for (const commenter of commenters) {
      await Comment.create({ text: 'Great post, thanks for sharing!', post: post._id, author: commenter._id });
    }
  }

  console.log('Creating messages...');
  for (let i = 0; i < 40; i++) {
    const sender = pick(users);
    const receiver = pick(sender.friends.length ? users.filter((u) => sender.friends.some((f) => String(f) === String(u._id))) : users);
    await Message.create({ sender: sender._id, receiver: receiver._id, text: 'Hey! How are you doing?' });
  }

  console.log(`Done. Created ${users.length + 1} users, ${groups.length} groups, ${posts.length} posts.`);
  console.log('Demo login: email "dana@example.com" / password "password123" (manager), or "admin@example.com" / "admin123" (admin).');
  await mongoose.disconnect();
}

run().catch((error) => { console.error(error); process.exit(1); });
